"use strict";
var frutas = ['maça', 'uva'];
frutas.push('banana');
console.log(frutas);
var diasemana = [];
diasemana.push('segunda');
diasemana.push(3);
console.log(diasemana);
var opcoes = [];
opcoes.push('ok');
opcoes.push(1);
opcoes.push(true);
console.log(opcoes);
